First Draft of the Search Screen and also logo
AmanTahiliani/PeerNotes pull request #4
Opened 2024-03-26 19:22 UTC by sahejpg

Made a logo and also made UI for searching for notes based on the filters we chose. Right now the Main Search screen is on the app screen just so I could see it, but feel free to comment it out whoever is working on the frontend too.

2024-03-26 21:33 UTC, AmanTahiliani commented
I love the Logo! I think the code changes look good to me. 
@afazio1  could comment better on the frontend aspect of it.

2024-03-26 21:34 UTC, AmanTahiliani approved these changes
Looks good to me. Great logo

2024-03-26 21:57 UTC, afazio1 requested changes
Looks awesome! Left comments about a few minor organization things and some thoughts I had. Feel free to let me know what you think!

2024-03-26 21:57 UTC, afazio1 commented on frontend/src/screens/MainScreenWrapper.css
Forgot to push this, but on my branch there is a `src/styles` folder for css files. You can add that folder the your branch and put this file there. Also remember to update the css import!

2024-03-26 21:57 UTC, afazio1 commented on frontend/src/assets/PeerNotes.png
Where is this image used? There seems to be a duplicate one `public/PeerNotes.png`

2024-03-26 21:57 UTC, afazio1 commented on frontend/src/App.tsx
> +      <div className="App" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
We could add something like `gap: 1` here for a little bit of spacing between image and MainSearch. Let me know if you think that would look good 👍

2024-03-26 21:57 UTC, afazio1 commented on frontend/src/screens/MainScreenWrapper.css
> +    width: 100%; /* fill the container width */
We could make all selects have a full width if we add `.filter-item { width: 100%; }`

2024-04-09 20:09 UTC, sahejpg commented on frontend/src/assets/PeerNotes.png
yeah there's a duplicate, will get rid of that

2024-04-09 20:13 UTC, merged